[package]
name = "assign"
version = "0.1.0"
edition = "2021"

[dependencies]
google-classroom1 = "5.0.4"
google-sheets4 = "5.0.4"
inquire = "0.7.5"
itertools = "0.13.0"
serde = "1.0.203"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
